#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="${ENV_FILE:-$SCRIPT_DIR/.env}"
ENV_TEMPLATE="${ENV_TEMPLATE:-$SCRIPT_DIR/env.template}"
COMPOSE_FILE="${COMPOSE_FILE:-$SCRIPT_DIR/docker-compose.yml}"
IMAGES_DIR="${IMAGES_DIR:-$SCRIPT_DIR/images}"
CERT_DIR="${CERT_DIR:-$SCRIPT_DIR/nginx/certs}"
MIN_FREE_MB="${MIN_FREE_MB:-2048}"

log_info()  { printf '[install] INFO  %s\n' "$*" >&2; }
log_error() { printf '[install] ERROR %s\n' "$*" >&2; }
die()       { log_error "$*"; exit 1; }

check_docker() {
    command -v docker >/dev/null 2>&1 \
        || die "Docker not found on PATH — install Docker Engine before running this installer."
    docker info >/dev/null 2>&1 \
        || die "Docker daemon is not reachable — is the docker service running, and are you in the docker group?"
}

check_compose() {
    docker compose version >/dev/null 2>&1 \
        || die "Docker Compose v2 not found — install the docker-compose-plugin package."
}

check_openssl() {
    command -v openssl >/dev/null 2>&1 \
        || die "openssl not found on PATH — install the openssl package before running this installer."
}

check_ports_free() {
    local port
    if ! command -v ss >/dev/null 2>&1; then
        # Fail visibly-open rather than silently-open: the operator should
        # know this check did not happen, so a port-binding failure later in
        # compose_up is not a surprise.
        log_info "'ss' not found — skipping the ports 80/443 availability check. If either port is already in use, bringing the stack up will fail later with a port-binding error."
        return 0
    fi
    for port in 80 443; do
        if ss -ltn 2>/dev/null | awk '{print $4}' | grep -q ":${port}\$"; then
            die "Port ${port} is already in use — stop the service using it before installing."
        fi
    done
}

check_disk_space() {
    local dir="$1" avail_mb
    avail_mb="$(df -Pm "$dir" 2>/dev/null | awk 'NR==2 {print $4}')" || avail_mb=""
    [[ "$avail_mb" =~ ^[0-9]+$ ]] \
        || die "Could not determine free disk space under ${dir} — 'df -Pm ${dir}' returned no usable value. Check that the path exists and is on a mounted filesystem."
    [[ "$avail_mb" -ge "$MIN_FREE_MB" ]] \
        || die "Only ${avail_mb} MB free under ${dir} — at least ${MIN_FREE_MB} MB free is required."
}

# The space that actually matters is under the Docker data root: that is
# where the loaded images and the Postgres volume land. The directory this
# bundle was extracted into is irrelevant to that (and is frequently on a
# different filesystem, e.g. removable media).
docker_data_root() {
    docker info --format '{{.DockerRootDir}}'
}

preflight_checks() {
    check_docker
    check_compose
    check_openssl
    check_ports_free
    local docker_root
    docker_root="$(docker_data_root)" \
        || die "Could not determine the Docker data root — 'docker info' failed; is the docker daemon running and are you in the docker group?"
    [[ -n "$docker_root" ]] \
        || die "Docker reported an empty data root — cannot check free space. Inspect 'docker info' output on this host."
    check_disk_space "$docker_root"
}

verify_manifest() {
    local root="$1" manifest="$1/manifest.sha256" err_file
    [[ -f "$manifest" ]] \
        || die "manifest.sha256 not found in ${root} — the bundle may be corrupt or incomplete."
    err_file="$(mktemp)"
    log_info "Verifying bundle integrity against manifest.sha256"
    if ! (cd "$root" && sha256sum -c manifest.sha256) >"$err_file" 2>&1; then
        log_error "Checksum verification failed — the following file(s) are missing or modified:"
        grep -v ': OK$' "$err_file" >&2 || true
        rm -f "$err_file"
        die "Bundle integrity check failed. Re-copy the bundle from a trusted source and retry."
    fi
    rm -f "$err_file"
    verify_no_unlisted_files "$root" "$manifest"
}

# `sha256sum -c` only checks files the manifest LISTS — it says nothing about
# files that were added to the tree afterwards. That matters here because
# docker-compose.yml bind-mounts ./initdb into Postgres's
# /docker-entrypoint-initdb.d/, where any added .sql/.sh file is executed on
# first boot. Compare the on-disk inventory against the manifest's path list
# and refuse to proceed on anything unlisted.
#
# Allow-list, mirroring build.sh's write_manifest() exclusion plus the two
# artifacts install.sh itself creates after the manifest was written (so a
# re-run of install.sh still verifies cleanly):
#   - manifest.sha256   (excluded by write_manifest by design)
#   - .env              (generated by configure_env on first run)
#   - nginx/certs/*     (generated by generate_tls_cert, or supplied by the
#                        operator before install)
verify_no_unlisted_files() {
    local root="$1" manifest="$2" listed actual extra
    listed="$(mktemp)"; actual="$(mktemp)"; extra="$(mktemp)"
    # sha256sum lines are "<hex>  <path>" (or "<hex> *<path>" in binary mode).
    # A leading './' is stripped on both sides so the comparison does not
    # depend on whether the manifest was generated with find's './' prefix.
    sed -E -e 's/^[0-9a-fA-F]+[[:space:]]+\*?//' -e 's|^\./||' "$manifest" \
        | LC_ALL=C sort > "$listed"
    ( cd "$root" && find . -type f \
        ! -name 'manifest.sha256' \
        ! -path './.env' \
        ! -path './nginx/certs/*' \
        -print ) | sed -E 's|^\./||' | LC_ALL=C sort > "$actual"
    LC_ALL=C comm -13 "$listed" "$actual" > "$extra"
    if [[ -s "$extra" ]]; then
        log_error "The following file(s) exist in the bundle but are NOT listed in manifest.sha256:"
        sed 's|^|  |' "$extra" >&2
        rm -f "$listed" "$actual" "$extra"
        die "Bundle integrity check failed: unlisted file(s) present. Files added after the bundle was built are not covered by the manifest and will not be trusted — re-copy the bundle from a trusted source and retry."
    fi
    rm -f "$listed" "$actual" "$extra"
}

configure_env() {
    if [[ -f "$ENV_FILE" ]]; then
        log_info ".env already exists at ${ENV_FILE} — leaving existing configuration untouched"
        return 0
    fi
    [[ -f "$ENV_TEMPLATE" ]] || die "env.template not found at ${ENV_TEMPLATE}"
    local pg_password
    pg_password="$(openssl rand -base64 24)" \
        || die "Failed to generate a random Postgres password with 'openssl rand' — check that openssl works on this host."
    # umask 077 in a subshell so the file is created 600 from the outset: a
    # plain create-then-chmod leaves a brief window in which the database
    # password is world-readable on a multi-user host. chmod below is kept as
    # defense in depth (and normalizes the mode if .env is created some other
    # way in future).
    ( umask 077 && sed "s|__POSTGRES_PASSWORD__|${pg_password}|" "$ENV_TEMPLATE" > "$ENV_FILE" ) \
        || die "Failed to write ${ENV_FILE} from ${ENV_TEMPLATE}"
    chmod 600 "$ENV_FILE"
    log_info "Generated ${ENV_FILE} with a random Postgres password (mode 600)"
}

generate_tls_cert() {
    local cert="$CERT_DIR/fullchain.pem" key="$CERT_DIR/privkey.pem"
    if [[ -f "$cert" && -f "$key" ]]; then
        log_info "TLS certificate already present at ${CERT_DIR} — leaving it in place"
        return 0
    fi
    if [[ -f "$cert" || -f "$key" ]]; then
        die "Found only one of fullchain.pem/privkey.pem in ${CERT_DIR} — remove the stray file or supply the matching one before re-running install.sh"
    fi
    mkdir -p "$CERT_DIR"
    log_info "Generating a self-signed TLS certificate (365 days) at ${CERT_DIR}"
    # `2>&1 >/dev/null` (in that order) discards openssl's stdout but routes
    # its stderr into the command substitution, so a failure reports openssl's
    # own diagnostic instead of aborting the script with no explanation at all.
    local openssl_err
    openssl_err="$(openssl req -x509 -nodes -newkey rsa:2048 \
        -keyout "$key" -out "$cert" -days 365 \
        -subj "/CN=guacamole.local" 2>&1 >/dev/null)" \
        || die "Failed to generate a self-signed TLS certificate in ${CERT_DIR}: ${openssl_err}"
    chmod 600 "$key"
}

# Every `image:` value declared in the compose file, one per line. Mirrors
# build.sh's compose_image_refs() so both halves agree on what "the images
# this bundle needs" means.
compose_image_refs() {
    awk '$1 == "image:" { print $2 }' "$COMPOSE_FILE"
}

# Proof that the load actually produced usable images: every image the
# compose file names must now resolve locally. Without this, a bundle whose
# tars were saved under the wrong name (or not at all) fails much later, and
# much less clearly, when compose cannot find the image.
verify_compose_images_present() {
    local ref missing=0
    [[ -f "$COMPOSE_FILE" ]] \
        || die "docker-compose.yml not found at ${COMPOSE_FILE} — the bundle may be corrupt or incomplete."
    while read -r ref; do
        [[ -n "$ref" ]] || continue
        if ! docker image inspect "$ref" >/dev/null 2>&1; then
            log_error "Image '${ref}', required by docker-compose.yml, is not present in the local Docker daemon after loading the bundled image tars."
            missing=1
        fi
    done < <(compose_image_refs)
    [[ "$missing" -eq 0 ]] \
        || die "One or more images required by docker-compose.yml were not loaded from ${IMAGES_DIR}. This bundle is incomplete or was built incorrectly — it cannot install without network access. Rebuild it with build.sh and re-transfer."
}

load_images() {
    local tar_file found=0
    for tar_file in "$IMAGES_DIR"/*.tar; do
        [[ -e "$tar_file" ]] || continue
        found=1
        log_info "Loading $(basename "$tar_file")"
        docker load -i "$tar_file" \
            || die "Failed to load image from ${tar_file} — the file may be truncated or corrupt; re-copy the bundle and retry."
    done
    [[ "$found" -eq 1 ]] || die "No image tars found in ${IMAGES_DIR} — the bundle may be corrupt or incomplete."
    verify_compose_images_present
}

compose_up() {
    local err_file
    err_file="$(mktemp)"
    # Captured rather than streamed so the failure message can carry docker
    # compose's own diagnostic, matching verify_manifest()'s pattern in this
    # same script. On an air-gapped host that diagnostic is often the only
    # thing available to work from.
    if ! ( cd "$SCRIPT_DIR" && docker compose --env-file "$ENV_FILE" -f "$COMPOSE_FILE" up -d ) >"$err_file" 2>&1; then
        log_error "Failed to bring up the compose stack. docker compose reported:"
        cat "$err_file" >&2 || true
        log_error "  -> run: (cd ${SCRIPT_DIR} && docker compose -f ${COMPOSE_FILE} logs)"
        rm -f "$err_file"
        die "Failed to bring up the compose stack — see the docker compose output above."
    fi
    rm -f "$err_file"
}

wait_healthy() {
    local timeout="${1:-180}" elapsed=0 services svc cid status unhealthy

    services="$(cd "$SCRIPT_DIR" && docker compose -f "$COMPOSE_FILE" config --services)" \
        || die "Failed to determine compose services"
    log_info "Waiting up to ${timeout}s for all services to report healthy"

    while (( elapsed < timeout )); do
        unhealthy=0
        for svc in $services; do
            cid="$(cd "$SCRIPT_DIR" && docker compose -f "$COMPOSE_FILE" ps -q "$svc")"
            if [[ -z "$cid" ]]; then
                unhealthy=1
                continue
            fi
            status="$(docker inspect --format '{{.State.Health.Status}}' "$cid" 2>/dev/null || echo "unknown")"
            [[ "$status" == "healthy" ]] || unhealthy=1
        done
        if [[ "$unhealthy" -eq 0 ]]; then
            log_info "All services healthy"
            return 0
        fi
        sleep 3
        elapsed=$((elapsed + 3))
    done

    log_error "Timed out waiting for services to become healthy. Current status:"
    ( cd "$SCRIPT_DIR" && docker compose -f "$COMPOSE_FILE" ps ) >&2 || true
    for svc in $services; do
        log_error "  -> run: (cd ${SCRIPT_DIR} && docker compose logs ${svc})"
    done
    die "Stack did not become healthy within ${timeout}s"
}

print_summary() {
    cat <<'EOF'

Guacamole is up.

  URL:    https://<this-host>/guacamole/
  Login:  guacadmin / guacadmin

  *** CHANGE THE DEFAULT guacadmin PASSWORD NOW ***
  Settings -> Users -> guacadmin -> change password, immediately after first login.

EOF
}

main() {
    preflight_checks
    verify_manifest "$SCRIPT_DIR"
    load_images
    configure_env
    generate_tls_cert
    compose_up
    wait_healthy 180
    print_summary
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    main "$@"
fi
